export const actionTypes = {
  // show all the products
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  // 
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  // Empty cart
  INITIALIZE_CART: "INITIALIZE_CART",
  //   Add items to cart
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  //Add or minus products from the cart
  UPDATE_PRODUCT_QTY_IN_CART: "UPDATE_PRODUCT_QTY_IN_CART",
  //   Remove products from the cart
  DELETE_PRODUCTS_FROM_CART: "DELETE_PRODUCTS_FROM_CART",

  INITIALIZE_WISHLIST: "INITIALIZE_WISHLIST",
  ADD_PRODUCT_TO_WISHLIST: "ADD_PRODUCT_TO_WISHLIST",
  DELETE_PRODUCTS_FROM_WISHLIST: "DELETE_PRODUCTS_FROM_WISHLIST",

  INITIALIZE_CATEGORIES: "INITIALIZE_CATEGORIES",
};
export const filterTypes = {
  INITIALIZE_FILTERS: "INITIALIZE_FILTERS",
  FILTERS: "FILTERS",
  CLEAR_FILTER: "CLEAR_FILTER",
};

export const addressTypes = {
  ADD_ADDRESS: "ADD_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
};
